FROM ubuntu:16.04
MAINTAINER aaron.pederson@gmail.com

RUN package install \
                    ansible \
                    build-essential \
                    emacs-nox \
                    fish \
                    git \
                    htop \
                    tmux \
                    zsh

RUN locale-gen \
               en_CA.UTF-8 \
               fr_CA.UTF-8

